# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
lang: en
title: Jekyll-IndieWeb
email: cedric@bousmanne.com
description: A Jekyll quick start to getting up and going with the indieweb.
# Webmentions - leave blank (remove "yes") if you would not like to receive & display webmentions from other sites
webmentions: yes

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: akyrho
github_username:  cedricbousmanne
instagram_username: akyrh0
flickr_username:
foursquare_username:
# Tumblr URL
tumblr_url:
# Linkedin profile URL - Expecting a full url, not username
linkedin_url: https://www.linkedin.com/in/bousmannecedric/
# Facebook profile URL - Expecting a full url, not username
facebook_url: https://www.facebook.com/cedric.bousmanne


# Can be over ridden with author: in Front Matter
author: Cédric Bousmanne

# Expecting a full url, not relative to site.url
author_img: https://pbs.twimg.com/profile_images/727192012504621056/NycTZi0P_400x400.jpg

# Build settings
markdown: kramdown

sass:
    style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist 
  - jekyll-font-awesome-sass

paginate: 5
